#pragma once

enum class Color {
    BLACK = 0, RED, GREEN, YELLOW, BLUE, MAGENTA, CYAN, WHITE,
    GRAY, RED_CLARO, GREEN_CLARO, YELLOW_CLARO, BLUE_CLARO, MAGENTA_CLARO, CYAN_CLARO, WHITE_BRILHANTE,
    FUNDO_BLACK, FUNDO_RED, FUNDO_GREEN, FUNDO_YELLOW, FUNDO_BLUE, FUNDO_MAGENTA, FUNDO_CYAN, FUNDO_WHITE,
    RESET, NEGRITO, SUBLINHADO, PISCANDO, INVERSO, OCULTO
};

