#pragma once

enum class Color {
    BLACK = 0, RED, GREEN, YELLOW, BLUE, MAGENTA, CYAN, WHITE,
    GRAY, LIGHT_RED, LIGHT_GREEN, LIGHT_YELLOW, LIGHT_BLUE, LIGHT_MAGENTA, LIGHT_CYAN, BRIGHT_WHITE,
    BG_BLACK, BG_RED, BG_GREEN, BG_YELLOW, BG_BLUE, BG_MAGENTA, BG_CYAN, BG_WHITE,
    RESET, BOLD, UNDERLINE, BLINKING, INVERSE, HIDDEN,

    // Constantes legadas para compatibilidade retroativa
    RED_CLARO = LIGHT_RED,
    GREEN_CLARO = LIGHT_GREEN,
    YELLOW_CLARO = LIGHT_YELLOW,
    BLUE_CLARO = LIGHT_BLUE,
    MAGENTA_CLARO = LIGHT_MAGENTA,
    CYAN_CLARO = LIGHT_CYAN,
    WHITE_BRILHANTE = BRIGHT_WHITE,
    FUNDO_BLACK = BG_BLACK,
    FUNDO_RED = BG_RED,
    FUNDO_GREEN = BG_GREEN,
    FUNDO_YELLOW = BG_YELLOW,
    FUNDO_BLUE = BG_BLUE,
    FUNDO_MAGENTA = BG_MAGENTA,
    FUNDO_CYAN = BG_CYAN,
    FUNDO_WHITE = BG_WHITE,
    NEGRITO = BOLD,
    SUBLINHADO = UNDERLINE,
    PISCANDO = BLINKING,
    INVERSO = INVERSE,
    OCULTO = HIDDEN
};

